name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - uses: mxcl/xcodebuild@50de62057fb935d18daedb23fb07ca4e62e4ca40 # v1.11.0
        with:
          platform: ${{ matrix.platform }}
          action: test
          scheme: SessionManager
          code-coverage: true
          upload-logs: always
